authentication/urls.py
from django.urls import path
from .views import UserRegister, UserLoginView
from django.contrib.auth.views import LogoutView
app_name = 'authentication'
urlpatterns = [
    path('SignUp/', UserRegister.as_view(),name='signup'),
    path('Login/',UserLoginView.as_view(),name='login'),
    path('Logout', LogoutView.as_view(next_page='authentication:login'),name='logout'),
]

todoapp/urls.py
from django.urls import path
from .views import TaskList, TaskDetailView, TaskCreateView, TaskUpdateView, TaskDeleteView
app_name = 'todoapp'
urlpatterns = [
    path('',TaskList.as_view(),name= 'tasklist'),
    path('task_detail/<int:pk>/', TaskDetailView.as_view(), name='taskdetail'),
    path('task_create/',TaskCreateView.as_view(),name='taskcreate'),
    path('task_detail/<int:pk>/update/', TaskUpdateView.as_view(),name='taskupdate'),
    path('task_detail/<int:pk>/delete/', TaskDeleteView.as_view(),name='taskdelete'),
]

todolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('', include('todoapp.urls')),
]

authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator
# Create your models here.

class User(AbstractUser):
    profile_photo = models.ImageField()
    phone_number = models.IntegerField(validators=[MinValueValidator(9000000000),MaxValueValidator(9999999999)], null=True, blank=True)
    

todoapp/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=50)
    description = models.TextField(max_length=5000)
    complete = models.BooleanField(default=False)
    create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['complete']
    
    def get_absolute_url(self):
        return reverse('todoapp:taskdetail', kwargs={'pk':self.pk})
        

authentication/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class SignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('first_name','last_name','username','email')

authentication/views.py
from django.shortcuts import render, redirect
from .models import User
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from .forms import SignUpForm
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.views import LoginView
#from django.contrib.auth import logout
from django.views import View
# Create your views here.

class UserRegister(SuccessMessageMixin,CreateView):
    form_class = SignUpForm
    #fields = ['first_name','last_name','username','email','password']
    template_name = 'authentication/sign_up.html'
    success_url = reverse_lazy('todoapp:tasklist')

    def get_success_message(self,cleaned_data):
        print(cleaned_data)
        return "Account Successfully Created"

class UserLoginView(SuccessMessageMixin,LoginView):
    template_name = 'authentication/login.html'

    def get_success_message(self,cleaned_data):
        print(cleaned_data)
        return "Logged In Success"
    
# class UserLogoutView(SuccessMessageMixin,View):
#     def get(self, request):
#         logout(request)
#         return redirect('todoapp:tasklist')
    
#     def get_success_message(self,cleaned_data):
#         print(cleaned_data)
#         return "Logout Success"

todoapp/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Task
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

class TaskList(LoginRequiredMixin,ListView):
    model = Task
    context_object_name = 'tasks'
    template_name = 'todoapp/tasklist.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = context['tasks'].filter(user=self.request.user)#display item related to logged in user only
        context['count'] = context['tasks'].filter(complete=False).count()
        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['tasks'] = context['tasks'].filter(title__icontains=search_input)
        context['search_input'] = search_input
        return context


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    context_object_name = 'tasks'
    template_name = 'todoapp/task_detail.html'

class TaskCreateView(LoginRequiredMixin,CreateView):
    model = Task
    fields = ['title','description','complete']
    context_object_name = 'tasks'
    template_name = 'todoapp/task_create.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TaskCreateView, self).form_valid(form)

class TaskUpdateView(LoginRequiredMixin,UpdateView):
    model = Task
    fields = '__all__'
    template_name='todoapp/task_update.html'

class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    context_object_name = 'tasks'
    template_name = 'todoapp/task_delete.html'
    success_url = reverse_lazy('todoapp:tasklist')

authentication/templates/authentication/login.html
{% extends 'todoapp/base.html' %}
{% load crispy_forms_tags %}
{% block title %}User Login{% endblock title %}
{% block body %}
<h1>Login</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Login">
</form>
<p>To Create Account: <a href="{% url 'authentication:signup' %}">Sign Up</a></p>
{% endblock body %}

authentication/templates/authentication/sign_up.html
{% extends 'todoapp/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Sign Up{% endblock title %}
{% block body %}
<h1>Sign Up</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Sign Up">
</form>

{% endblock body %}

todoapp/templates/todoapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=DynaPuff&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'todoapp/base.css' %}">
</head>
<body>
    <div class="container">
    {% include 'todoapp/messages.html' %}
    <form action="" method="get">
        <input type="text" name="search-area" value="{{ search_input }}">
        <input type="submit" value="Search">
    </form>
    
    {% block body %}
    {% endblock body %}
    </div>
</body>
</html>

todoapp/templates/todoapp/messages.html
{% if messages %}
{% for message in messages %}
{{ message }}
{% endfor %}
{% endif %}

todoapp/templates/todoapp/task_create.html
{% extends 'todoapp/base.html' %}
{% block title %}Task Add{% endblock title %}
{% block body %}
    <h1>Enter a new task</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add">
    </form>
{% endblock body %}

todoapp/templates/todoapp/task_delete.html
{% extends 'todoapp/base.html' %}
{% block title %}Delete {{tasks.title|title }}{% endblock title %}
{% block body %}
    <h1>Delete Task</h1>
    <form action="" method="post">
        {% csrf_token %}
        <h2>Do you want to delete {{ tasks.title|title }}?</h2>
        <input type="submit" value="Delete">
        <button type="submit"><a href="{% url 'todoapp:taskdetail' tasks.id %}">Go back</a></button>
    </form>
{% endblock body %}

todoapp/templates/todoapp/task_detail.html
{% extends 'todoapp/base.html' %}
{% block title %}{{ tasks.title|title }}{% endblock title %}
{% block body %}
    <H1>Task Detail</H1>
    <p>Task Title: {{ tasks.title|title }}</p>
    <p>Description: {{ tasks.description }}</p>
    <p>Status: {{ tasks.complete }}</p>
    <p>Date Created: {{ tasks.create }}</p>
    <p>Author: {{ tasks.user|title }}</p>
    <button><a href="{% url 'todoapp:taskupdate' tasks.pk %}">Update</a></button>
    <button><a href="{% url 'todoapp:taskdelete' tasks.pk %}">Delete</a></button>
{% endblock body %}

todoapp/templates/todoapp/task_list.html
{% extends 'todoapp/base.html' %}
{% block title %}Task List{% endblock title %}
{% block body %}
<a href="{% url 'authentication:signup' %}">Sign Up</a>
{% if request.user.is_authenticated %}
{{ request.user }}
<a href="{% url 'authentication:logout' %}">Logout</a>
{% else %}
<a href="{% url 'authentication:login' %}">Login</a>
{% endif %}
    <h1>Task List </h1>
    <table>
        <tr>
            <th>Item</th>
            <th></th>
        </tr>
        <tr>
            {% for task in tasks %}
            <td>{{ task.title|title }}</td>
            <td><a href="{% url 'todoapp:taskdetail' task.id %}">View</a></td>
        </tr>
            {% empty %}
            <h1>No items on the list</h1>
            {% endfor %}
    </table>
    <button><a href="{% url 'todoapp:taskcreate' %}">Task Create</a></button>

{% endblock body %}

todoapp/templates/todoapp/task_update.html
{% extends 'todoapp/base.html' %}
{% block title %}Update{% endblock title %}
{% block body %}
    <H1>Update Task</H1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>

{% endblock body %}